FROM python:3.11-slim

# Install Tesseract
RUN apt-get update && apt-get install -y tesseract-ocr

# Set the working directory
WORKDIR /app

# Copy all project files to the container
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set Tesseract path explicitly
ENV TESSERACT_PATH="/usr/bin/tesseract"

# Start the app
CMD ["gunicorn", "app:app"]
